# Generated by Django 3.2.5 on 2022-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=25)),
                ('doctor_name', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic_name',
            field=models.TextField(default='HMS clinic'),
            preserve_default=False,
        ),
    ]
